---
title: "Kurudu NP morphology"
author: "Carl Börstell"
#date: "29 January 2019"
site: bookdown::bookdown_site
output: 
  bookdown::html_document2:
    toc: true
    toc_float: true
bibliography: kurudu_NP.bib
#csl: ussfl.csl
---

# Preface {-#preface}
> *The following document is the result of an intro class to field linguistics in 2010. The basic "fieldwork" took place at Stockholm University with a native speaker[^maury] of Kurudu (ISO: `kjr`; see map below)[^kaipuri] during approximately 10 elicitation sessions (see also Section 1 below). Thus, it is not meant to be a comprehensive guide to Kurudu language, nor does it make any claims of being completely accurate. However, due to the limited resources/documentation for this language, I decided to make this fragment available, with the hopes of future in-depth work being conducted on the language. (NB: Some smaller typographical mistakes have been corrected from the original paper.)*

Carl Börstell, Nijmegen, 30 January, 2019

[^maury]: The informant, Mr. Maury, passed away approximately three years after the data for this course were collected (see https://swepaeu.wordpress.com/2013/09/20/dorinus-ruben-maury-r-i-p/).

[^kaipuri]: Our informant, Mr. Maury, referred to his language as *Kaipuri*, after his village. Thus, we referred to the language using this label, which is why the document below will refer to the Kaipuri language. Whether there are great variation between the villages on the Kurudu island is not known to me, and all current classifications appear to use the label *Kurudu* for the language on the island.


```{r, echo=FALSE, warning=FALSE}
library(lingtypology)
map.feature(c("Kurudu"),
            minimap = TRUE,
            minimap.position = "topright",
            zoom.level = 5)
```
Figure 1: The location of the Kurudu language (plotted with the [`lingtypology`](https://ropensci.github.io/lingtypology/index.html) package [@moroz2017])

# Introduction
This paper on the morphosyntax of the NP in Kaipuri is the result of a fieldwork project within a course on field linguistics at the Department of Linguistics, Stockholm University during the fall semester of 2010. We had the opportunity to work with a speaker of Kaipuri (ISO: kjr), a language of the Kaipuri village on Kurudu Island, off the East coast of Yapen Island, West Papua (Indonesia). During the course, we had about two sessions a week with the speaker, with whom we worked group-wise for five weeks. The author of this paper was in a group together with Francesca Di Garbo and Yvonne Agbetsoamedo, and our group focused our work on investigating the morphosyntax of the noun phrase.

This paper is divided into to major segments: the first (section 2) deals with some basic morphology that concerns the NP; and the second (section 3) deals more with the syntax of the NP. Please bear in mind that this work should be seen as a first draft of a basic grammatical description, still containing several gaps and unresolved matters.

I would like to take this opportunity to thank Mr. Dorinus Ruben Maury for participating as the language consultant for this project, who made this work even possible. Thank you. 

## Glossing used for this paper
The glossing convention for this paper follows that of the [Leipzig Glossing Rules](https://www.eva.mpg.de/lingua/resources/glossing-rules.php), but the specific glosses used in this paper are given below for convenience.

Gloss | Meaning
---|---
1 | first person
2 | second person
3 | third person
ANIM | animate
DIST | distal
HUM | human
INANIM | inanimate
INT | intensifier
MED | medial
NHUM | non-human
PL | plural
POSS | possessive
POSTP | postposition
PREP | preposition
PROX | proximal
SG | singular

Since verbal inflectional paradigms are outside the scope of this investigation, verb stems will receive an inflected lexical gloss when the translation of it corresponds to, for instance, past tense. Whether the form is actually inflected for tense or not is not of concern for the present study. The code given below the translation is a reference to the audio file from which the example is taken.

# The Morphology of the NP

## Number inflection
Kaipuri seems to consistently make a singular/plural-distinction on noun phrases. The plural is the marked category, whereas the singular is unmarked for number. When the NP carries a numeral determiner, plural tends to be unmarked on the NP. Number is marked on the NP with an enclitic that attaches to the last element of the core NP (see further section 3.2 below).

(1)

a.
> *diu=pi*  
bird=MED  
‘Bird.’  
(CB_101116_RM_002)


b.
> *diu=pe=si*  
bird=MED=PL  
‘Birds.’  
(CB_101116_RM_002)


c.
> *una si-knau=pe=si si-sibuja*  
dog 3PL-white=MED=PL 3PL-fell  
‘The white dogs fell’  
(CB_101214_RM_003)


## Deictic markers
Kaipuri has an extensively used system of marking spatial deixis on noun phrases. Based on the translation and consultation of our informant, there seems to be a three-way distinction: proximal, which is used for objects close by the speaker; medial, which is used for objects some distance away from the speaker (but may be close to the addressee); and distal, which seems to be quite distant to both speaker and addressee (even as far away as not to be seen by the speaker). All the markers function as enclitics attached to the core NP. The medial markers seems to be in allophonic variation between a form mainly used with the singular (*=pi*), and another mainly used with the plural (*=pe*).

(2)
a.
> *una=ne sibuja*  
dog=PROX fell  
‘The dog (here) fell’  
(CB_101214_RM_001)

b.
> *una=ne=si si-sibuja*  
dog=PROX=PL 3PL-fell  
‘The dogs (here) fell’  
(CB_101214_RM_001)

c.
> *una=pi sibuja*  
dog=MED fell  
‘The dog (there) fell’  
(CB_101214_RM_001)
 
d.
> *una=pe=si si-sibuja*  
dog=MED=PL 3PL-fell  
‘The dogs (there) fell’  
(CB_101214_RM_001)

e.
> *una=wa sibuja*  
dog=DIST fell  
‘The dog (over there) fell’  
(CB_101214_RM_001)
 
f.
> *una=wa=si si-sibuja*  
dog=DIST=PL 3PL-fell  
‘The dogs (over there) fell’  
(CB_101214_RM_001)

The medial marker seems to be the default marker for all nouns. When asking the speaker for a translation of a single lexical noun, the reply was in nearly all instances used with a deictic marker, and when not having a specific referent, it would be presented with the medial marker clitic. When used in a clause, the inclusion of a deictic marker seems to be obligatory for lexical nouns.

(3)

> *una sibuja*  
dog fell  
‘A dog fell.’  
(CB_101214_RM_001)

According to @anceaux1961, the element *pe* is said to mark definiteness in the language: “The suffix *--pe* seems to denote definiteness.” [@anceaux1961: 158]. This seems not to be the case, since there is quite obviously a deictic paradigm in which *=pi/pe* is one of the forms. However, since spatial deixis is a way of singling out specific referents, one could in fact say that they indirectly have a definiteness function as well, although this would then suggest that the *=pi/pe*-form might be the least definite of the forms, since it seems to be the form used when not actually having a specific referent to refer to.

Looking at another language in the same area -- Biak -- we find the same distinction of spatial deicitc markers, roughly in the same form as those of Kaipuri: “Formatives expressing relative distance from the speaker: ‘here’ (PRX), (*--ne*), ‘there (MED)’ (*--i*, clause medially *--ya*), and ‘yonder (DIST)’ (*--wa*). The distance for an entity to be qualified as PRX etc. depends on its volume. A distance of 5 meters would qualify a house as being PRX, but a scorpion as DIST.” [@steinhauer2005: 815]

Thus, there seems to be an almost identical system in Kaipuri, although the notion of distance relative to volume of the object has not been investigated in our study.

### Animacy distinction in the =pi/pe-marker
There is a distinction of animacy concerning the *=pi/pe*-markers. According to our language  consultant, the *=pi/pe* form may only be used with things, not with people. It seems as though the distinction is of [+/-HUMAN], where the element *p* may in fact be a marker denoting [--HUMAN]. Thus, there would be one morpheme denoting spatial deixis (*i/e*) and another denoting non-human referent (*p*).

(4)

a.
> *diu=p-i*  
bird=NHUM-MED  
‘Bird.’  
(CB_101116_RM_002)

b.
> *diu=p-e=si*  
bird=NHUM-MED=PL  
‘Birds.’  
(CB_101116_RM_002)

c.
> *kabor=i*  
boy=MED  
‘Boy.’  
(CB_101214_RM_001)

d.
> *kabor=e=si*  
boy=MED=PL  
‘The boys’  
(CB_101207_RM_001)

e.
> *\*kabor=p-e=si*  
boy=NHUM-MED=PL  
‘The boys’  
(CB_101207_RM_001)

Whether or not the *p*-element is actually a marker of [--HUMAN] referents or not is yet to be investigated. Some obviously human referents still take the *=pi/pe* forms, although these seem to be of the kind which would not surprisingly act more as a non-human referent (e.g. ‘child’).[^phonology]

[^phonology]: Perhaps the *=pi*/*=i* distinction relies more on phonological context -- i.e. *p*-insertion intervocalically (CB 2019).

(5)
> *vrangri=p-e=si*  
child=NHUM-MED=PL  
‘The children’  
(CB_101116_RM_002)

However, since this area has not been extensively studied, the remainder of this analysis will group the segments *=i/e* and *=pi/pe* as variations of a morpheme simply denoting spatial deixis (i.e. MED).

## Animacy and gender
For the numeral words in Kaipuri, there seems to be a distinction of animacy and gender when using a numeral as a determiner in the NP. For inanimate head nouns, the numeral appears in its basic form. However, when the head is an animate noun, the first syllable of the numeral is replaced by a different morpheme, which seems to be different with regard to the natural gender of at least  human referents.

(6)

a.
> *una man-tor si-osr*  
dog ANIM.M-three 3PL-stand  
‘Three dogs are standing’  
(CB_101123_RM_005)

b.
> *pena bo-ru=ne*  
pen INANIM-two=PROX  
‘Two pens’  
(CB_101215_RM_001)

c.
> *antukri man-du*  
child ANIM.M-two  
‘Two boys’ / ‘Two sons’  
(CB_101122_RM_001)

d.
> *antukri min-du*
child ANIM.F-two  
‘Two girls’ / ‘Two daughters’  
(CB_101122_RM_001)

The use of numeral determiners is discussed further in section 3.2.3 below.


# The Syntax of the NP

## The minimal NP
In Kaipuri, the most basic type of NP consists of a single noun, proper noun or a pronoun. Proper nouns and pronouns do not seem to carry morphological inflections. However, the lexical NP’s tend to be marked with the deictic marker in most cases. For instance, with a single noun in the NP, the deictic marker seems to be obligatory.

(7)

a. 
> *i sibu*  
3SG fell  
‘He fell’  
(CB_101123_RM_005)

b.
> *ivon sibu*  
yvonne fell  
‘Yvonne fell’  
(CB_101123_RM_005)

c.
> *una=wa sibu*  
dog=DIST fell  
‘The dog fell’  
(CB_101214_RM_001) 

d.
> *\*una sibu*  
(CB_101214_RM_001)

The plural marker *=si* is obligatorily marked on the NP, where it comes directly after the deictic marker.

(8)

> *una=wa=si si-sibuja*  
dog=DIST=PL 3PL-fell  
‘The dogs fell’  
(CB_101214_RM_001)

However, for nouns that are [+HUMAN], neither deictic marker nor plural marker seem to be obligatory.

(9)

> *kabor si-sibuj*  
boy 3PL-fell  
‘The boys fell’  
(CB_101214_RM_001)

## The core NP
For the Kaipuri NP, there seems to be a core NP which is the part of the NP that receives the nominal inflections (i.e. enclitics attach to this level of the NP). Anything outside this core NP will not receive these nominal inflections, but still seem to be clearly included in the extended NP as to its function (see further in section 3.3 below).

### Possessive constructions
The possessive construction in the Kaipuri NP seems to be based on juxtapositioning. This is most obvious when we have proper nouns as possessors.

(10)

a.
> *apner antukri=p-i*  
Apner child=NHUM-MED  
‘Apner’s child’  
(CB_101223_RM_004)

b.
> *apner antukri man-du*  
Apner child ANIM-two  
‘Apner’s two children’  
(CB_101223_RM_004)

c.
> *apner mandukri antukri=p-i*  
Apner younger.brother child=NHUM-MED  
‘Apner’s younger brother’s child’  
(CB_101223_RM_004) 

With pronominal possessors, there seems to be a system of several possessive pronouns for some persons. The distribution and use of these has not been fully investigated, though there might be a difference based on alienability.

(11)

a.
> *aj du=p-i*  
1SG.POSS head=NHUM-MED  
‘My head’  
(CB_101116_RM_002)

b.
> *aj ndokmi boru*  
1SG.POSS eye two  
‘My two eyes’  
(CB_101115_RM_003)

c.
> *ajne una=p-i*  
1SG.POSS dog=NHUM-MED  
‘My dog’  
(CB_101214_RM_004)

For third person singular, the possessive pronoun seems to always be of a form identical to the basic pronominal form.

(12)

a.
> *i sinani*  
3SG mother  
‘His/her mother’  
(CB_101116_RM_004)

b.
> *i sibu*  
3SG fell  
‘S/he fell’  
(CB_101123_RM_005)

The complete paradigm for possessive pronominal forms has not yet been established. However, for the lexical possessors (and perhaps also for proper noun possessors), there might in fact be a morpheme coordinating the possessor and possessum which has the form *ne*. Since this form seems to occur along the *=ne* denoting proximal deixis, it seems as though the morpheme has some other function. This morpheme does not seem to be obligatory.

(13)

a.
> *iman antukri*  
man child  
‘The man’s child.’  
(CB_101122_RM_001)

b.
> *iman ne antukri*  
man POSS? child  
‘The man’s child.’  
(CB_101122_RM_001) 

c.
> *una=ne ne anam=p-e*  
dog=MED POSS? food=NHUM-MED  
‘The dog’s food.’  
(CB_101122_RM_001)

d.
> *librek ne anam=p-e*  
Librek POSS? food=NHUM-MED  
‘Librek’s food.’  
(CB_101122_RM_001)

Whether this *ne* is actually a morpheme coordinating possession or if it is simply a possession verb can not be concluded from our data. However, it would be interesting to speculate in the fact that this ne particle and the proximal marker *=ne* actually have a common origin. It is widely known that possessive constructions are often derived from locative expressions, mainly those denoting an object being close to its possessor [cf. @lyons1967;@freeze1992;@heine1997]. However, whether this particle shares an origin with the deictic marker can be neither confirmed nor rejected from our data.

### Adjectival modifiers
Within the core NP, Kaipuri allows for more elements than just a single noun. These will be described in the following section.

In Kaipuri, the adjectival words seem to be rather verbs than proper adjectives since they often function as the clause predicate and take verbal inflection. However, it seems as though these attributive verbs have a different status than other verbs when it comes to their inclusion in the NP, and they will thus be referred to as adjectives in this description. They can be used as independent predicates, but when they are included in the NP, the morphology will show that it is actually part of the NP and not an independent predicate.

(14)

a.
> *una kinau=p-i sibu*  
dog white=NHUM-MED fell  
‘The white dog fell’  
(CB_101214_RM_002)

b.
> *\*una=p-i kinau sibuja*  
(CB_101214_RM_002)

c.
> *una si-knau=p-e=si si-sibuja*  
dog 3PL-white=NHUM-MED=PL 3PL-fell  
‘The white dogs fell’  
(CB_101214_RM_003)

d.
> *\*una=p-e=si si-knau si-sibuja*  
(CB_101214_RM_003)

An adjective may also function by itself as a complete NP. 

(15)

> *kinau=wa sibu*  
white=MED fell  
‘The white one fell’  
(CB_101214_RM_002)

When the adjectives function as predicate, only the NP will receive the nominal inflections. This is what seems to differentiate adjectives from prototypical verbs, since genuine verbs do not take nominal inflection.

(16)

a.
> *una kinau=p-i*  
dog white=NHUM-MED  
‘The white dog’  
(CB_101207_RM_002)

b.
> *una=p-i kinau*  
dog=NHUM-MED white  
‘The dog is white’  
(CB_1012[missing])

c.
> *\*una si-tur=p-e=si*  
dog 3PL-sit=NHUM-MED=PL  
‘The sitting dogs’  
(CB_101207_RM_003)

It is also possible to include an intensifying morpheme in NP’s with an adjective. This will appear as a suffix on the adjective, before the nominal inflections.

(17)

a.
> *una si-knau=p-e=si*  
dog 3PL-white=NHUM-MED=PL  
‘The white dogs’  
(CB_101207_RM_002)

b.
> *una si-knau-po=p-e=si*  
dog 3PL-white-INT=NHUM-MED=PL  
‘The very white dogs’  
(CB_101207_RM_002)

### Numeral determiners
Numerals may also be included in the NP. However, Kaipuri seems to have a system where the numeral determiners are different depending on the animacy of the head. Inanimate nouns seem to take the regular numeral word as determiner, whereas the animate nouns take a modified form where the first syllable of the numeral is replaced with *man--* (where the final nasal gets assimilated to the place of articulation of the first phoneme of the numeral stem). Only the numeral in the inanimate form seems to take the distance marker. 

(18)

a.
> *una man-tor si-osr*  
dog ANIM-three 3PL-stand  
‘Three dogs are standing’  
(CB_101123_RM_005)

b.
> *pena bo-ru=ne*  
pen INANIM-two=PROX  
‘Two pens’  
(CB_101215_RM_001)

A numeral -- at least with animate inflection -- may also function by itself as a complete NP.

(19)

> *man-sandi si-osnau ...*
ANIM-one 3PL-stand  
‘One is standing ...’  
(CB_101123_RM_002)

The plural marker seems to never occur on either the head noun or the numeral, hence the numeral itself seems to be able to specify plurality by its own semantics sufficiently.

### Multiple modifiers
It is possible to include possessor, adjective and numeral in the NP.

(20)

a.
> *una kinau man-sandi sibu*  
dog white ANIM-one fell  
‘One white dog fell’  
(CB_101214_RM_005)

b.
> *ajne una si-metra mam-berim*  
1SG.POSS dog 3PL-black ANIM-five  
‘My five black dogs’  
(CB_101122_RM_002)

However, it might be the case that the numerals—at least with the animate inflection—may in fact function predicatively. This is suspected from the fact that the NP will not receive nominal inflection when the numeral is a part of the NP (see example 20a) but will receive it when the numeral is not followed by a verb (see examples 21a-b)—i.e. when the numeral is obviously inside the NP, we do not see any inflections, but we get inflections when we do not have a verb. The inflections will always go on the adjective, if present.

(21)

a.
> *una kinau=p-i man-sandi*  
dog white=NHUM-MED ANIM-one  
‘One white dog’  
(CB_101214_RM_004) 

b.
> *una si-knau=p-e=si man-tor*  
dog 3PL-white=NHUM-MED=PL ANIM-three  
‘Three white dogs’  
(CB_101214_RM_004)

c.
> *\*una=p-i kinau man-sandi*  
(CB_101214_RM_004)

The order of the adjective and numeral is fixed, where the numeral always follows the adjective: [Poss (*ne*) N A Num].

(22)

> *\*una man-sandi kinau=p-i sibu*  
dog ANIM-one white=NHUM-MED fell  
‘One white dog fell’  
(CB_101214_RM_005)

### NP coordination
In Kaipuri, it is possible to coordinate several NP’s by simply having the conjunction tutro between them.

(23)

a.
> *maria tutro paulina si-sina*  
Maria CONJ Paulina 3PL-mother  
‘Maria and Paulina’s mother’  
(CB_101116_RM_004)

b.
> *i tiuŋ-garu awa tutro kale*  
3SG sit-between 2SG CONJ Calle  
‘S/he is sitting between you and Calle’  
(CB_101116_RM_004)


## The extended NP
The NP in Kaipuri may feature additional elements, however, these can be seen as more peripheral to the NP since they never receive nominal morphology. Thus, we might say that the extended NP may include further elements, but unlike the core NP, these peripheral elements will never receive the nominal inflections.

### Predicative modifier
Kaipuri may include a modifying element in the NP which seems to be a VP. The fact that this element is actually included in the NP can be seen from the following examples, in which some have the element as the predicate of a main clause, but those included in the NP have another predicate which is the predicate of the whole clause. 

(24)

a.
> *[pena=wa vianau medja rivane] mimetra*  
pen=DIST lie table under black  
‘The pen lying under the table is black’  
(CB_101215_RM_001)

b.
> *[pena=w boru si-vanau medja rivane] si-metra*  
pen=DIST two 3PL-lie table under 3PL-black  
‘The two pens lying under the table are black’  
(CB_101215_RM_001)

cf.

c.
> *[pena=ne] vianau medja rivane*  
pen=DIST lie table under  
‘The pen is lying under the table’  
(CB_101215_RM_001)

d.
> *[pena boru-ne] vanau medja rivane*  
pen two=PROX lie table under  
‘The two pens are lying under the table’  
(CB_101215_RM_001)

### Spatial modifiers
Some evidence of NP’s with a modifying element looking like a PP have been found. However, it appears as though the informant favors this element to include a verbal element, in which case it is actually the kind of modifying complement described as a predicative modifier in section 3.3.1 above. Nonetheless, the type of complement without the verbal element is possible.

(25)

> *[pena boru medja rivane] si-metra*  
pen two table under 3PL-black  
‘The two pens under the table are black’  
(CB_101215_RM_001)

In most cases, a word that seems to be some kind of general adposition *nau* is used in these constructions. It is usually placed before its object noun, but there are instances where it actually follows it.

(26)

a.
> *[ana=ne [nau unajvev=ne]] mandara*  
food=PROX PREP pot=PROX hot  
‘The food in the pot is hot’ (The word unajvevr may in fact mean ‘plate’)  
(CB_101215_RM_001)

b.
> *[imane [nau otobus]] kiruajne*  
man:PROX PREP bus tall  
‘The man on the bus is tall’  
(CB_101215_RM_001) 

c.
> *[pena=si [medja rivane nau]] si-mimetra*  
pen=PL table under POSTP 3PL-black  
‘The pens under the table are black’  
(CB_101215_RM_001)
 
# References
 